<?php
/**
 * Created by PhpStorm.
 * User: TEMIT
 * Date: 24/03/2017
 * Time: 05:00
 */

/**
 * Implements hook_form_alter().
 */

function form_change_form_alter(&$form, &$form_state, $form_id) {
  if($form_id == 'node_type_form'){
      switch($form_id){
		case 'node_type_form':
		  $form['display']['node_submitted']['#default_value'] = 0 ;
		   $form['add_text']['#markup'] = t('Applying Hook Form Alter to display settings');
		  break;
	  }


  }
}

function form_change_update_7100(){
  $modules = array(
    'formchange',
	'myform_change',
  );
  db_delete('system')
	->condition('name', $modules, 'IN')
	->condition('type', 'module')
	->execute();

}